name: LLMGE (Slurm)

on:
  workflow_dispatch:

jobs:
  submit_slurm:
    runs-on: [self-hosted]

    steps:
      - name: Use existing scratch repo
        run: |
          cd /home/hice1/tnguyen831/scratch/llm-guided-evolution-cicd
          git fetch origin
          git reset --hard origin/new_main

      - name: Submit Slurm job
        run: |
          cd /home/hice1/tnguyen831/scratch/llm-guided-evolution-cicd
          JOBID=$(sbatch --parsable slurm_llmge.sbatch)
          echo "Submitted Slurm job: $JOBID"
